-- Compatibility pointer only; this file is intentionally non-executable.
-- Canonical Exam DB schema: ../../mysql-init/init-exam-db.sql
-- Docker Compose mounts the canonical MySQL 8 script for fresh-volume initialization.
-- Keep schema changes in the canonical file and Exam Service-owned additive migration code.
