-- Compatibility pointer only; this file is intentionally non-executable.
-- Canonical Course DB schema: ../../mysql-init/init-course-db.sql
-- Docker Compose mounts the canonical MySQL 8 script for fresh-volume initialization.
-- Keep schema changes in the canonical file and Course Service-owned additive migrations.
