-- Compatibility pointer only; this file is intentionally non-executable.
-- Canonical User DB schema: ../../mysql-init/init-user-db.sql
-- Docker Compose mounts the canonical MySQL 8 script for fresh-volume initialization.
-- Keep schema changes in the canonical file and User Service-owned additive migrations.
