-- Compatibility pointer only; this file is intentionally non-executable.
-- Canonical Payment DB schema: ../../mysql-init/init-payment-db.sql
-- Docker Compose mounts the canonical MySQL 8 script for fresh-volume initialization.
-- Keep schema changes in the canonical file and Payment Service-owned migration process.
